### ISSUE TITLE
Add support for ripping imgur account

### ISSUE THREAD

**Issue by tyilo** [4pr0n/rip#5] opened 2013-07-07 01:44 UTC
Something like http://tyilo.imgur.com/all/ or just http://tyilo.imgur.com/

**Comment by 4pr0n** [comment] 2013-07-27 03:53
The ripper can already grab full albums from an imgur account.

The problem is when there's images but no albums. If we support ripping images, then we will lose album support. If we have album support, then we can't grab the images as well without grabbing duplicates.

I think album support is more important the image support, so marking as WontFix.

**Closed as completed by 4pr0n** 2013-07-27 03:53 UTC
Labels: wontfix
