### ISSUE TITLE
Running from the command line returns 'The system cannot find the file specified'

### ISSUE THREAD

**Issue by IT6uru** [4pr0n/rip#13] opened 2013-08-10 12:33 UTC
I'm not sure what is going on here, but it seems that it can't find the directory for putting the rip in, even if I create the directory it wants, it deletes it (on linux), and refuses to find it. I've tried on both windows and linux.

**Comment by 4pr0n** [comment] 2013-08-10 20:25
What's the full dump of the error?
What album are you trying to rip? 
What is the exact command being executed at the command line??

**Comment by IT6uru** [comment] 2013-08-10 22:41
1.)      [!] rip.py ended with error message:
          [Error 2] The system cannot find the file specified: 'rips\tumblr_doitbig
          shutitdown'

2.)    It appears to only effect tumblr, imgur works fine. I've tried multiple tumblr sites, none seem to work.

3.)    python rip.py  tumblrurl

**Comment by 4pr0n** [comment] 2013-08-11 11:00
Do you have a tumblr API key in `/sites/tumblr_api.key`? An API key is required to rip from tumblr.

I tried removing / invalidating my key and I wasn't able to reproduce the error.

**Comment by ressu** [comment] 2013-08-21 05:15
I am able to reproduce this. The error is most likely caused by the script trying to open the directory after ripping.

So the root cause is not the error itself, but the fact that it's unable to rip from tumblr and that would most likely be caused by the missing API key.

**Comment by 4pr0n** [comment] 2013-08-23 15:35
I forgot I added the "open directory after ripper" option.

Yea, it seems like the tumblr ripper isn't working, likely due to an invalid/missing API key.

Closing issue since IT6uru hasn't commented in 2 weeks.

@IT6uru  Feel free to reopen if you still have issue after entering a valid tumblr API key

**Closed as completed by 4pr0n** 2013-08-23 15:35 UTC
